### ISSUE TITLE
ref. link to docs

### ISSUE THREAD

**Issue by paolodina** [PrimarySite/django-transitions#4]
reference to RTD:

https://django-transitions.readthedocs.io/en/latest/

**Comment by cleder** [comment]
You mean in `setup.py` and Pypi?

**Comment by paolodina** [comment]
Sorry for not being clear. The ticket was about adding a reference to django-transitions rendered docs to `README.rst`.

**Comment by cleder** [comment]
It is on the [Docs Passing] badge, is this not intuitive? Should there be another explicit link?

**Comment by paolodina** [comment]
Yep now it is. I think I missed  that badge since I'm on github (many project explicitly add the documentation link to the readme). Good to know, for me it's fine now.
