### ISSUE TITLE
Locking mechanism for concurrency

### ISSUE THREAD

**Issue by hunterclarke** [PrimarySite/django-transitions#5]
We're considering a couple of different libraries for implementing a state machine in our Django app. One of the requirements we have is that writes or transitions are safe in a concurrent environment.

I see that transitions has threadsafe locking https://github.com/pytransitions/transitions#-threadsafe-ish-state-machine, however we're looking for something that will also lock at the database level.

Based on the documentation, I'm unsure if this library provides that. Could someone help me out?

Thanks

**Comment by cleder** [comment]
No threadsafe locking was not considered and is likely to be out of scope for this library. When you get the django object you could `select_for_update()` to lock the object. Note that django-transistion does not save the object but you have to do this yourself so locking is entirely in your hands https://docs.djangoproject.com/en/3.0/ref/models/querysets/#select-for-update

**Comment by hunterclarke** [comment]
Great, thanks for the explanation and for being so responsive @cleder.

**Comment by cleder** [comment]
This looks like a good source:

https://lincolnloop.com/blog/distributed-locking-django/

Distributed Locking in Django
As you start scaling an application out horizontally (adding more servers/instances), you may run into a problem that requires distributed locking. That's a fancy term, but the concept is simple. Sometimes you have to be sure that when a block of code is running (usually modifying data somewhere), no other instances runs that same block of code. Ideally, you can design your code not to require locks, but sometimes it is inevitable.
